      - name: Send Message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="ðŸš€ Automate your business with AI! Get the kit here: https://girisbhut.gumroad.com/l/sgdoet"
