name: Telegram Auto Bot
on:
  workflow_dispatch:

jobs:
  post_to_telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ नमस्ते! आपकी ऑटोमैटिक मशीन अब सफलतापूर्वक कनेक्ट हो गई है।"
